"""add_premium_fields_to_balance_ledger

Revision ID: 19cd1e83e15d
Revises: h8i9j0k1l2m3
Create Date: 2026-01-25 19:23:30.888644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cd1e83e15d'
down_revision: Union[str, None] = 'h8i9j0k1l2m3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_ledger', sa.Column('amount_premium', sa.Integer(), nullable=False))
    op.add_column('balance_ledger', sa.Column('balance_premium_before', sa.Integer(), nullable=False))
    op.add_column('balance_ledger', sa.Column('balance_premium_after', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.create_unique_constraint(None, 'transactions', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=True)
    op.drop_column('balance_ledger', 'balance_premium_after')
    op.drop_column('balance_ledger', 'balance_premium_before')
    op.drop_column('balance_ledger', 'amount_premium')
    # ### end Alembic commands ###
