"""add_bot_channels_table

Revision ID: 98ce8ee64640
Revises: 003_refactor
Create Date: 2026-01-01 19:55:12.679555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ce8ee64640'
down_revision: Union[str, None] = '003_refactor'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_username', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=False),
    sa.Column('added_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_channels_added_by', 'bot_channels', ['added_by_user_id'], unique=False)
    op.create_index(op.f('ix_bot_channels_channel_id'), 'bot_channels', ['channel_id'], unique=True)
    op.add_column('checks', sa.Column('check_type', sa.String(length=20), nullable=False))
    op.add_column('checks', sa.Column('content_type', sa.String(length=20), nullable=False))
    op.add_column('checks', sa.Column('amount_premium_months', sa.Integer(), nullable=False))
    op.add_column('checks', sa.Column('recipient_username', sa.String(length=255), nullable=True))
    op.add_column('checks', sa.Column('recipient_id', sa.BigInteger(), nullable=True))
    op.add_column('checks', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('checks', sa.Column('required_channel', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('checks_code_key'), 'checks', type_='unique')
    op.drop_index(op.f('ix_checks_code'), table_name='checks')
    op.create_index(op.f('ix_checks_code'), 'checks', ['code'], unique=True)
    op.create_index('ix_checks_created_at', 'checks', ['created_at'], unique=False)
    op.create_index('ix_checks_creator_id', 'checks', ['creator_id'], unique=False)
    op.drop_constraint(op.f('orders_order_key_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_order_key'), table_name='orders')
    op.create_index(op.f('ix_orders_order_key'), 'orders', ['order_key'], unique=True)
    op.drop_constraint(op.f('promo_codes_code_key'), 'promo_codes', type_='unique')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_unique_constraint(op.f('promo_codes_code_key'), 'promo_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orders_order_key'), table_name='orders')
    op.create_index(op.f('ix_orders_order_key'), 'orders', ['order_key'], unique=False)
    op.create_unique_constraint(op.f('orders_order_key_key'), 'orders', ['order_key'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_checks_creator_id', table_name='checks')
    op.drop_index('ix_checks_created_at', table_name='checks')
    op.drop_index(op.f('ix_checks_code'), table_name='checks')
    op.create_index(op.f('ix_checks_code'), 'checks', ['code'], unique=False)
    op.create_unique_constraint(op.f('checks_code_key'), 'checks', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('checks', 'required_channel')
    op.drop_column('checks', 'password')
    op.drop_column('checks', 'recipient_id')
    op.drop_column('checks', 'recipient_username')
    op.drop_column('checks', 'amount_premium_months')
    op.drop_column('checks', 'content_type')
    op.drop_column('checks', 'check_type')
    op.drop_index(op.f('ix_bot_channels_channel_id'), table_name='bot_channels')
    op.drop_index('ix_bot_channels_added_by', table_name='bot_channels')
    op.drop_table('bot_channels')
    # ### end Alembic commands ###
